version: "3.9"
services:
  delay-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    environment:
      - ENV_USER=${DB_USER}
      - ENV_PASS=${DB_PASS}
      - ENV_HOST=${DB_HOST}
      - ENV_DB=${DB_TO_USE}
    ports:
      - "3000:3000"

  delay-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    environment:
      - ENV_USER=${DB_USER}
      - ENV_PASS=${DB_PASS}
      - ENV_HOST=${DB_HOST}
      - ENV_DB=${DB_TO_USE}
    ports:
      - "5000:5000"

  delay-db:
    restart: always
    build: ./database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      - MONGO_INITDB_DATABASE=${DB_TO_USE}
    volumes:
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"

  delay-tool:
    build:
      context: ./tool
      target: prod
      dockerfile: Dockerfile
      args:
        ARG_USER: ${DB_USER}
        ARG_PASS: ${DB_PASS}
        ARG_HOST: ${DB_HOST}
        ARG_DB: ${DB_TO_USE}
    ports:
      - "5011:5011"
    working_dir: /delay-tool
